const MessageType = Object.freeze({
    EVERYTHING: Symbol( '*' ),
    TRANSACTION_BEGIN: Symbol('transactionBegin'),
    TRANSACTION_END: Symbol('transactionEnd'),
    CONFIG_SET: Symbol( 'configurationSet' ),
    CONFIG_CLEAR: Symbol( 'configurationClear' ),
    CONFIG_TOGGLE: Symbol( 'configurationToggle' ),
    USER_NAVIGATION: Symbol('userNavigation'),
    USER_INPUT_CLEAR: Symbol( 'userInputClear' ),
    USER_INPUT_SET: Symbol( 'userInputSet' ),
    USER_INPUT_SEND: Symbol( 'userInputSend' ),
    CONVERSATION_ID: Symbol( 'conversationId' ),
    CONVERSATION_NEW: Symbol( 'conversationNew' ),
    CONVERSATION_CLEAR: Symbol( 'conversationClear' ),
    CONVERSATION_SELECT: Symbol( 'conversationSelect' ),
    MESSAGE: Symbol( 'message' ),
});